# Importing Libraries

In [21]:
import pandas as pd
import numpy as np
import os.path as osp

pd.options.display.max_columns = 100
pd.options.display.float_format = "{:,.2f}".format

# Definitions

In [22]:
DATA_PATH = osp.join('..', 'data','data_cleaned.csv')
TARGET = 'qt_adjuvante_-_pratica_clinica'

categorical_features=[
      'etilismo'
    , 'tabagismo'
    , 'status_menopausa'
    , 'lateralidade'
    , 'histologia'
    , 'multifocal'
    , 'estadiamento_patologico'
    , 'estadio_n'
    , 'ihq_lfn'
    , 'ec'
    , 'gh'
    , 'risco_clinico'
    , 'ial'
    , 'cirurgia'
    , 'bls'
    , 'disseccao_axilar'
    , 'regime_qt'
    , 'te_adjuvante'
    , 'switch'
    , 'te'
    , 'supressao_ovariana'
    , 'monitoracao_de_estradiol_ultrass'
    , 'supressao_ovariana_adequada'
    , 'radioterapia_adjuvante'
    , 'recorrencia'
    , 'sitio'
    # , 'obito'
    ]

numeric_features = [
      'altura'
    , 'idade_ao_diagnostico'
    , 'imc'
    , 'ki67'
    , 'odxrs'
    , 'peso'
    , 're'
    , 'rp'
    , 'tamanho'
    , 'tils'
    , 'tempo_para_cirurgia'
 ]

selected_features = set(categorical_features + numeric_features + [TARGET])

# Reading Data

In [23]:
df = pd.read_excel('../data/Planilha Dados clínicos.xlsx', sheet_name = 0, header = 1)
df.head()

,CASOS,Prontuário,Data Nascimento,Data Diagnostico,IDADE ao diagnóstico,Peso,Altura,IMC,Etilismo,Tabagismo,Status Menopausa,Lateralidade,HISTOLOGIA,MULTIFOCAL,Estadiamento patológico,Estadio N,IHQ LFN,Tamanho,EC,GH,Risco clínico,RE,RP,Ki67,TILS,IAL,DATA DA CIRURGIA,CIRURGIA,BLS,Dissecção axilar,ODXRS,QT ADJUVANTE - PRÁTICA CLÍNICA,Regime QT,TE ADJUVANTE,Data da TE,Switch,TE,Supressão OVARIANA,Monitoração de Estradiol ultrass,Supressão ovariana adequada,RADIOTERAPIA ADJUVANTE,RECORRENCIA,SITIO,DATA DA RECORRENCIA,OBITO,DATA DO OBITO,DATA ULTIMA CONSULTA
0,BP,"4,060,199.00",1966-07-30 00:00:00,2018-05-05 00:00:00,51.00,59.70,162.00,2022-07-22 00:00:00,0.00,0.00,2.00,1.00,1.00,0.00,8.00,0.00,1.00,25.00,3.00,2.00,2.00,90.00,90.00,20.00,999.00,1.00,2018-05-24 00:00:00,2.00,0.00,1.00,6.00,0.00,999.00,1.00,2018-07-01 00:00:00,2.00,1.00,999.00,999.00,999.00,1.00,0.00,999.00,0,999.00,999.00,NaT
1,BP,"4,292,706.00",1948-09-18 00:00:00,2019-04-01 00:00:00,70.00,56.00,159.00,2022-09-24 00:00:00,0.00,0.00,2.00,1.00,1.00,0.00,8.00,0.00,1.00,30.00,3.00,3.00,2.00,90.00,90.00,50.00,999.00,0.00,2019-07-23 00:00:00,2.00,0.00,1.00,31.00,1.00,3.00,1.00,2020-03-05 00:00:00,2.00,2.00,999.00,999.00,999.00,1.00,0.00,999.00,0,999.00,999.00,NaT
2,BP,"2,986,483.00",1966-11-11 00:00:00,2015-06-19 00:00:00,48.00,61.80,176.00,20.0,2.00,1.00,1.00,1.00,3.00,1.00,6.00,0.00,1.00,8.00,1.00,1.00,1.00,98.00,95.00,16.00,999.00,0.00,2015-07-09 00:00:00,6.00,0.00,1.00,17.00,0.00,999.00,1.00,2015-08-01 00:00:00,2.00,1.00,1.00,0.00,0.00,1.00,0.00,999.00,0,999.00,999.00,NaT
3,BP,"4,225,534.00",1963-07-07 00:00:00,2019-05-20 00:00:00,55.00,67.00,155.00,2022-09-27 00:00:00,0.00,0.00,2.00,1.00,1.00,1.00,8.00,0.00,1.00,18.00,3.00,3.00,2.00,100.00,10.00,10.00,999.00,0.00,2019-06-07 00:00:00,1.00,0.00,1.00,33.00,1.00,3.00,1.00,2019-12-13 00:00:00,2.00,2.00,999.00,999.00,999.00,0.00,0.00,999.00,0,999.00,999.00,NaT
4,BP,"4,116,395.00",1967-11-25 00:00:00,2012-12-01 00:00:00,45.00,58.00,165.00,2022-03-21 00:00:00,0.00,0.00,1.00,2.00,1.00,1.00,7.00,3.00,1.00,15.00,1.00,2.00,1.00,95.00,95.00,12.00,999.00,0.00,2012-12-07 00:00:00,6.00,0.00,1.00,9.00,0.00,999.00,1.00,2013-01-01 00:00:00,2.00,1.00,1.00,0.00,0.00,0.00,1.00,1.00,2018-11-19 00:00:00,999.00,999.00,2022-01-28

# Renaming columns

In [24]:
# !pip install unidecode
import unidecode

def standardize_column_name(col):
    col = unidecode.unidecode(col)
    return col.replace(' ', '_').lower()

df.columns = [standardize_column_name(col) for col in df.columns]

# Data Cleaning

## Standardize Null, True and False

In [25]:
standardize_values_dict = {
    'etilismo': { 
          0: 999 #Desconhecido
        , 1: 0 #Não 
        , 2: 1 #Sim
    }
    , 'tabagismo': { 
          0: 999 #Desconhecido
        , 1: 0 #Não 
        , 2: 1 #Sim
    }
    , 'status_menopausa': {
        3:999 #Desconhecido
    }
    , 'lateralidade': {
        4:999 #Desconhecido
    }
    , 'ihq_lfn': {
          0:1 #. Sim
        , 1:0 #. Não
    }
    , 'bls': {
          0: 1 #. Sim
        , 1: 0 #. Não
    }
    , 'te_adjuvante':{
        3:0 #Não
    }
    , 'supressao_ovariana_adequada': {
          0: 1 #. Sim
        , 1: 0 #. Não
    }
}

In [26]:
for col, values in standardize_values_dict.items():
    df[col] = df[col].replace(values)

## Treating missing rows

In [27]:
# Drop rows with all missing values
df.dropna(how = 'all', inplace = True)

# Fill missing values with 999
df = df.fillna(999)

# Feature Engineering

In [28]:
# replacing 999 with NaN
df[['peso','altura']] = df[['peso','altura']].replace(999, np.nan)

# Recalculate IMC
df['imc'] = df['peso'] / ((df['altura']/100) ** 2)

# Calculate time until surgery
df[['data_diagnostico', 'data_da_cirurgia']] = df[['data_diagnostico', 'data_da_cirurgia']].apply(pd.to_datetime, errors = 'coerce')
df['tempo_para_cirurgia'] = (df['data_da_cirurgia'] - df['data_diagnostico']).dt.days

# Adjusting Dtypes

In [29]:
# Fill missing values with 999
df = df.fillna(999)

dtypes = {
    'prontuario': int
    , 'idade_ao_diagnostico': int
    , 'peso': float
    , 'altura': float
    , 'imc': float # will be recalculated
    , 'etilismo': int
    , 'tabagismo': int
    , 'status_menopausa': int
    , 'lateralidade': int
    , 'histologia': int
    , 'multifocal': int
    , 'estadiamento_patologico': int
    , 'estadio_n': int
    , 'ihq_lfn': int
    , 'tamanho': float
    , 'ec': int
    , 'gh': int
    , 'risco_clinico': int
    , 're': float
    , 'rp': float
    , 'ki67': float
    , 'tils': float
    , 'ial': int
    , 'cirurgia': int
    , 'bls': int
    , 'disseccao_axilar': int
    , 'odxrs': int
    , 'qt_adjuvante_-_pratica_clinica': int
    , 'te_adjuvante': int
    , 'supressao_ovariana_adequada': int
    , 'regime_qt' : int
    , 'switch' : int
    , 'te' : int
    , 'supressao_ovariana' : int
    , 'monitoracao_de_estradiol_ultrass' : int
    , 'radioterapia_adjuvante' : int
    , 'recorrencia' : int
    , 'sitio' : int
}

# Apply dtypes
df = df.astype(dtypes)

## Preprocessing

In [30]:
# dropping missing values on the target
df.dropna(subset=[TARGET], inplace=True)

In [31]:
# defining categorical features
df[categorical_features] = df[categorical_features].fillna('missing')
df[categorical_features] = df[categorical_features].astype(str)

# defining numeric features
df[numeric_features] = df[numeric_features].astype('float')

# defining o target
df[TARGET] = df[TARGET].astype('int')

In [32]:
# replacing 999 with NaN
df.replace([999,'999','999.0'], np.nan, inplace = True)

# Final DataFrame

In [33]:
df.sample(10)

,casos,prontuario,data_nascimento,data_diagnostico,idade_ao_diagnostico,peso,altura,imc,etilismo,tabagismo,status_menopausa,lateralidade,histologia,multifocal,estadiamento_patologico,estadio_n,ihq_lfn,tamanho,ec,gh,risco_clinico,re,rp,ki67,tils,ial,data_da_cirurgia,cirurgia,bls,disseccao_axilar,odxrs,qt_adjuvante_-_pratica_clinica,regime_qt,te_adjuvante,data_da_te,switch,te,supressao_ovariana,monitoracao_de_estradiol_ultrass,supressao_ovariana_adequada,radioterapia_adjuvante,recorrencia,sitio,data_da_recorrencia,obito,data_do_obito,data_ultima_consulta,tempo_para_cirurgia
90,BP,2895156,1969-02-05 00:00:00,2014-07-05,45.00,44.00,157.00,17.85,0,0,1,1,1,0,6,0,0,10.00,1,2,1,95.00,90.00,15.00,NaN,0,2014-07-23,3,1,1,10.00,0.00,NaN,1,2014-08-28 00:00:00,2,1,2,1,0,0,0,NaN,NaN,NaN,NaN,2022-01-10,18.00
6,BP,464921,1977-05-25 00:00:00,2020-11-05,43.00,45.00,158.00,18.03,0,0,1,2,1,1,5,0,0,5.00,1,3,1,50.00,0.00,50.00,50.00,0,2020-12-12,3,1,1,48.00,1.00,3,1,2021-06-28 00:00:00,2,1,1,0,1,0,0,NaN,0,NaN,NaN,2021-12-15,37.00
98,BP,4864455,1966-11-30 00:00:00,2021-10-25,53.00,83.00,162.00,31.63,0,0,2,2,1,1,8,0,0,25.00,3,1,1,100.00,5.00,5.00,NaN,1,2021-11-26,2,1,1,32.00,1.00,3,1,2022-03-23 00:00:00,2,1,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN,2022-03-23,32.00
100,BP,2601597,1963-06-11 00:00:00,2011-03-17,48.00,70.00,175.00,22.86,0,0,1,1,1,0,7,0,0,10.00,1,2,1,90.00,95.00,15.00,NaN,0,2011-03-23,2,1,1,16.00,0.00,NaN,1,2011-07-12 00:00:00,0,2,2,1,0,1,0,NaN,NaN,NaN,NaN,2022-02-08,6.00
8,BP,4569571,1962-01-09 00:00:00,2020-07-02,58.00,NaN,155.00,NaN,NaN,1,2,1,1,1,7,0,0,14.00,1,2,1,100.00,0.00,5.00,5.00,0,2020-09-28,2,1,1,25.00,0.00,NaN,1,2020-12-13 00:00:00,2,2,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN,2021-04-19,88.00
58,BP,4030802,1976-09-13 00:00:00,2018-03-07,43.00,70.00,174.00,23.12,0,0,1,1,1,0,7,0,0,16.00,1,2,1,95.00,90.00,10.00,NaN,0,NaT,2,1,1,11.00,0.00,NaN,1,2019-11-12 00:00:00,0,2,1,1,0,1,0,NaN,NaN,NaN,NaN,2021-12-17,NaN
67,BP,4874786,1983-12-30 00:00:00,2013-11-01,28.00,60.00,165.00,22.04,0,0,1,1,1,0,6,0,0,9.00,1,2,1,70.00,50.00,20.00,NaN,0,2013-12-03,3,1,1,17.00,0.00,NaN,2,2014-02-10 00:00:00,2,1,2,1,0,0,1,1,2021-10-20 00:00:00,NaN,NaN,2021-11-03,32.00
62,BP,4770594,1988-04-05 00:00:00,2021-04-01,32.00,60.00,170.00,20.76,0,0,1,1,1,0,7,0,0,11.00,1,2,1,99.00,85.00,15.00,NaN,0,2021-05-18,3,1,1,10.00,0.00,NaN,1,2021-07-22 00:00:00,1,2,1,0,0,0,0,NaN,NaN,NaN,NaN,2021-12-03,47.00
85,BP,4556342,1980-03-13 00:00:00,2020-06-25,41.00,66.00,165.00,24.24,1,0,1,1,1,0,7,0,0,16.00,1,2,1,90.00,90.00,10.00,NaN,0,2020-07-07,2,1,1,13.00,0.00,NaN,1,2020-12-15 00:00:00,0,1,2,1,0,1,0,NaN,NaN,NaN,NaN,2022-02-01,12.00
97,BP,4930591,1963-07-12 00:00:00,2017-06-23,53.00,60.00,165.00,22.04,0,0,2,1,1,0,7,0,0,12.00,1,3,2,90.00,80.00,10.00,NaN,0,2017-06-23,3,1,1,5.00,0.00,NaN,1,2017-08-20 00:00:00,2,2,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,2022-01-19,0.00

# Saving New DataFrame

In [34]:
df.to_excel('../data/data_cleaned.xlsx', index = False)
df.to_csv('../data/data_cleaned.csv', index = False)